biblat_manager/webapp/main/__init__.py
# -*- coding: utf-8 -*-
from flask import Blueprint
from flask_breadcrumbs import default_breadcrumb_root

main = Blueprint('main', __name__)
default_breadcrumb_root(main, '.')

from . import views  # NOQA

biblat_manager/webapp/main/views.py
# -*- coding: utf-8 -*-
import socket
from flask import (request,
                   session,
                   current_app,
                   redirect,
                   url_for,
                   abort,
                   render_template,
                   flash)
from flask_babelex import gettext as _, lazy_gettext as __
from flask_breadcrumbs import register_breadcrumb
from flask_login import current_user, login_user, logout_user, login_required
from biblat_schema.models import Fasciculo
from flask_mongoengine import Pagination

from . import main
from biblat_manager.webapp import babel, controllers
from biblat_manager.webapp.forms import (
    RegistrationForm, LoginForm, EmailForm, PasswordForm, FasciculoForm
)
from biblat_manager.webapp.models import User
from biblat_manager.webapp.utils import get_timed_serializer


@main.route('/', methods=['GET', 'POST'])
@register_breadcrumb(main, '.', __('Inicio'))
@login_required
def index():
    data = {
        'html_title': 'Biblat Manager - Index'
    }
    flash('You successfully read this important success message.', 'success')
    flash('You successfully read this important error message.', 'error')
    flash('You successfully read this important warning message.', 'warning')
    flash('You successfully read this important info message.', 'info')
    return render_template('main/index.html', **data)


@main.route('/revistas', methods=['GET', 'POST'])
@register_breadcrumb(main, '.revistas', __('Revistas'))
@login_required
def revistas():
    data = {
        'html_title': 'Biblat Manager - Revistas'
    }
    return render_template('main/index.html', **data)


# i18n
@babel.localeselector
def get_locale():
    langs = current_app.config.get('LANGUAGES')
    lang_from_headers = request.accept_languages.best_match(list(langs.keys()))

    if 'lang' not in list(session.keys()):
        session['lang'] = lang_from_headers

    if not lang_from_headers and not session['lang']:
        # Si no se puede detectar el idioma se asigna el predeterminado
        session['lang'] = current_app.config.get('BABEL_DEFAULT_LOCALE')

    return session['lang']


@main.route('/set_locale/<string:lang_code>/')
def set_locale(lang_code):
    langs = current_app.config.get('LANGUAGES')

    if lang_code not in list(langs.keys()):
        abort(400, _(u'Código de idioma inválido'))

    # Guardar lang_code en sesión
    session['lang'] = lang_code

    if request.referrer is None:
        return redirect(url_for('main.index'))
    return redirect(request.referrer)


@main.route('/menutoggle/')
def set_menutoggle():
    session['menutoggle'] = 'open' \
        if session.get('menutoggle', '') == '' else ''
    return session['menutoggle']


@main.route('/logout')
@login_required
def logout():
    logout_user()
    return redirect(url_for('.login'))


@main.route('/login', methods=['GET', 'POST'])
def login():
    if current_user.is_authenticated:
        return redirect(url_for('.index'))
    form = LoginForm()
    if request.method == 'POST' and form.validate():
        user = User.objects(email=form.email.data).first()
        if user and user.check_password_hash(form.password.data) \
                and user.email_confirmed:
            login_user(user, remember=form.remember.data)
            flash(_('Sesión iniciada como %s' % user.email), 'success')
            return redirect(session.get('next') or url_for('.index'))
        if not user:
            flash(_('Usuario no registrado'), 'error')
        if user and not user.check_password_hash(form.password.data):
            flash(_('Contraseña incorrecta'), 'error')
        if user and not user.email_confirmed:
            flash(_('Correo electrónico no verificado'), 'error')
    return render_template('auth/login.html', form=form)


# USER
@main.route('/usuarios', methods=['GET', 'POST'])
@main.route('/usuarios/<int:page>', methods=['GET', 'POST'])
@register_breadcrumb(main, '.users', __('Usuarios'))
@login_required
def list_users(page=1):
    # TODO: implementación de borrado de usuarios
    # TODO: implementación de reenvío de correo de confirmación
    order_by = request.args.get('order_by', None)
    column_list = {
        'username': _('Nombre de usuario'),
        'email': _('Correo electrónico'),
        'email_confirmed': _('Correo verificado?'),
    }
    users = User.objects.order_by(order_by).paginate(page=page, per_page=10)
    data = {
        'html_title': 'Biblat Manager - %s' % _('Usuarios'),
        'users': users,
        'order_by': order_by,
        'column_list': column_list
    }
    return render_template('main/users.html', **data)


@main.route('/usuarios/detalle/<user_id>', methods=['GET', 'POST'])
@register_breadcrumb(main, '.users.detail', __('Detalle'),
                     endpoint_arguments_constructor=lambda: {
                         'user_id': request.view_args['user_id']
                     })
@login_required
def user_detail(user_id):
    user = User.get_by_id(user_id)
    data = {
        'user': user
    }
    return render_template('main/user.html', **data)


@main.route('/usuarios/editar/<user_id>', methods=['GET', 'POST'])
@register_breadcrumb(main, '.users.edit', __('Editar'),
                     endpoint_arguments_constructor=lambda: {
                         'user_id': request.view_args['user_id']
                     })
@login_required
def user_edit(user_id):
    # TODO: permitir la actualización de usuarios sin actualizar contraseña
    user = User.get_by_id(user_id)
    form = RegistrationForm(obj=user)
    if request.method == 'POST' and form.validate():
        existing_user = User.get_by_email(form.email.data)
        if existing_user is None or user.id == existing_user.id:
            update_user = User.get_by_id(user_id)
            update_user.username = form.username.data
            update_user.email = form.email.data
            update_user.password = form.password.data
            update_user.save()
            flash(_('Usuario actualizado correctamente!'), 'info')
            if user.email != update_user.email:
                user.email_confirmed = False
                user.save()
                try:
                    # TODO: enviar email de actualización
                    was_sent, error_msg = update_user.send_confirmation_email()
                except (ValueError, socket.error) as e:
                    was_sent = False
                    error_msg = str(e)
                # Enviamos el email de confirmación al usuario.
                if was_sent:
                    flash(_('Se envío un correo de confirmación a: %(email)s',
                            email=update_user.email), 'info')
                else:
                    flash(_('Ocurrió un error en el envío del correo de '
                            'confirmación  a: %(email)s %(error_msg)s',
                            email=update_user.email, error_msg=error_msg),
                          'error')
        else:
            flash(_('El correo electrónico ya esta registrado'), 'error')
    return render_template('forms/register.html', form=form)


@main.route('/usuarios/agregar', methods=['GET', 'POST'])
@register_breadcrumb(main, '.users.add', __('Agregar'))
@login_required
def user_add():
    form = RegistrationForm()
    if request.method == 'POST' and form.validate():
        existing_user = User.get_by_email(form.email.data)
        if existing_user is None:
            user_data = {
                'username': form.username.data,
                'email': form.email.data,
                'password': form.password.data
            }
            user = User(**user_data).save()
            try:
                was_sent, error_msg = user.send_confirmation_email()
            except (ValueError, socket.error) as e:
                was_sent = False
                error_msg = str(e)
            # Enviamos el email de confirmación al usuario.
            if was_sent:
                flash(_('Se envío un correo de confirmación a: %(email)s',
                        email=user.email), 'info')
            else:
                flash(_('Ocurrió un error en el envío del correo de '
                        'confirmación  a: %(email)s %(error_msg)s',
                        email=user.email, error_msg=error_msg),
                      'error')
            return redirect(url_for('main.user_add'))
        else:
            flash(_('El correo electrónico ya esta registrado'), 'error')
    return render_template('forms/register.html', form=form)


@main.route('/user/confirm/<token>')
def confirm_email(token):
    try:
        ts = get_timed_serializer()
        email = ts.loads(token,
                         salt=current_app.config.get('TOKEN_EMAIL_SALT'),
                         max_age=current_app.config.get('TOKEN_MAX_AGE'))
    except Exception:  # posibles exepciones: https://pythonhosted.org/itsdangerous/#exceptions
        abort(404)

    user = User.get_by_email(email)
    if not user:
        abort(404, _('Usuario no encontrado'))

    controllers.set_user_email_confirmed(user)
    flash(_('Email: %(email)s confirmado com éxito!', email=user.email), 'success')
    return redirect(url_for('.index'))


@main.route('/reset/password', methods=['GET', 'POST'])
def reset():
    form = EmailForm()

    if request.method == 'POST' and form.validate():
        user = User.get_by_email(form.email.data)
        if not user:
            flash(_('Usuario no registrado'), 'error')
            return render_template('auth/reset.html', form=form)
        if not user.email_confirmed:
            user.send_confirmation_email()
            return render_template('auth/unconfirmed_email.html')

        was_sent, error_msg = user.send_reset_password_email()
        if was_sent:
            flash(_('Se enviaron instrucciones para recuperar su contraseña '
                    'al correo: %(email)s', email=user.email), 'info')
        else:
            flash(_('Ocurrió un problema al enviar el correo con las '

biblat_manager/webapp/templates/main/about.html
{% extends "sidebar_layout.html" %}
{% block content %}
            <div class="col-sm-6 col-lg-6">
                {% include "top_nav.html" %}
                {{ _('Revista') }}
            </div>
{% endblock %}

biblat_manager/webapp/templates/main/documento.html
{% extends "sidebar_layout.html" %}
{% block content %}
            <div class="col-sm-6 col-lg-6">
                {% include "top_nav.html" %}
                {{ _('Documento') }}
            </div>
{% endblock %} 

biblat_manager/webapp/templates/main/fasciculo.html
{% extends "sidebar_layout.html" %}
{% block content %}
            <div class="col-sm-6 col-lg-6">
                {% include "top_nav.html" %}
                {{ _('Fascículo') }}
            </div>
{% endblock %} 

biblat_manager/webapp/templates/main/index.html
{% extends "sidebar_layout.html" %}
{% block content %}
            <div class="col-sm-12 col-lg-12">
                <h4>{{ _('Bienvenido a Biblat Manager') }}</h4>
            </div>
{% endblock %}

biblat_manager/webapp/templates/main/user.html
{% extends "sidebar_layout.html" %}
{% from "_helpers.html" import bool_formatter %}
{% block content %}
<div class="col-md-8">
    <div class="card">
        <div class="card-header">
            <i class="fa fa-user"></i><strong class="card-title pl-2">{{ _('Datos de usuario') }}</strong>
        </div>
        <div class="card-body">
            <div class="table-responsive">
                <table class="table">
                    <tbody>
                        <tr>
                            <td><i class="fa fa-id-badge"></i> {{ _('ID') }}:</td>
                            <td>{{ user.id }}</td>
                        </tr>
                        <tr>
                            <td><i class="fa fa-user-o"></i> {{ _('Nombre de usuario') }}:</td>
                            <td>{{ user.username }}</td>
                        </tr>
                        <tr>
                            <td><i class="fa fa-envelope-o"></i> {{ _('Correo electrónico') }}:</td>
                            <td>{{ user.email }}</td>
                        </tr>
                        <tr>
                            <td><i class="fa fa-envelope-open-o"></i> {{ _('Correo electrónico verificado') }}?</td>
                            <td>{{ bool_formatter(user.email_confirmed) }}</td>
                        </tr>
                    </tbody>
                </table>
            </div>
        </div>
    </div>
</div>
{% endblock %}

biblat_manager/webapp/templates/main/users.html
{% extends "sidebar_layout.html" %}
{% from "_helpers.html" import bool_formatter, render_navigation %}
{% block content %}
    <div class="content mt-3">
        <div class="animated fadeIn">
            <div class="row">
            <!--iframe src="{{url_for('user.index_view')}}" style="width:100%;height:100%"></iframe-->
            <!--object type="text/html" data="{{url_for('user.index_view')}}"-->
        </object>

            <!--div class="col-md-12">
                <div class="card">
                    <div class="card-body">
                        <ul class="nav nav-tabs">
                          <li class="nav-item">
                            <a class="nav-link active" href="#">{{ _('Listado (%s)' % users.total) }}</a>
                          </li>
                          <li class="nav-item">
                            <a class="nav-link" href="{{ url_for('main.user_add') }}">{{ _('Agregar') }} <i class="fa fa-user-plus"></i></a>
                          </li>
                        </ul>
                        <div class="table-responsive">
                            <table class="table table-striped table-bordered table-hover model-list">
                                <thead>
                                  <tr>
                                      <th></th>
                                      {% for column, column_name in column_list.items() %}
                                          {% set order_class = 'sorting_asc' if order_by == column else '' %}
                                          {% set order_class = 'sorting_desc' if order_by and order_by[1:] == column else order_class %}
                                          {% set column_order = '-{0}'.format(column) if order_class == 'sorting_asc' else column %}
                                          <th class="sorting {{ order_class }}">
                                              <a href="{{ url_for('main.list_users', order_by=column_order) }}">
                                                  {{ column_name }}
                                              </a>
                                          </th>
                                      {% endfor %}
                                  </tr>
                                </thead>
                                <tbody>
                                    {% for user in users.items %}
                                        <tr>
                                            <td class="text-center">
                                                <a class="icon" href="{{ url_for('main.user_detail', user_id=user.id) }}" title="{{ _('Ver registro') }}">
                                                  <span class="fa fa-eye glyphicon glyphicon-eye-open"></span>
                                                </a>
                                                <a class="icon" href="{{ url_for('main.user_edit', user_id=user.id) }}" title="{{ _('Editar registro') }}" >
                                                    <span class="fa fa-pencil glyphicon glyphicon-pencil"></span>
                                                </a>
                                                {% if not user.email_confirmed %}
                                                    <a class="icon" href="#" title="{{ _('Enviar correo de confirmación') }}" >
                                                        <span class="fa fa-envelope glyphicon glyphicon-envelope"></span>
                                                    </a>
                                                {% endif %}
                                            </td>
                                            {% for column in column_list %}
                                                {% if user[column] | is_bool %}
                                                    <td class="text-center">{{ bool_formatter(user[column]) }}</td>
                                                {% else %}
                                                    <td>{{ user[column] }}</td>
                                                {% endif %}
                                            {% endfor %}
                                        </tr>
                                    {% endfor %}
                                </tbody>
                            </table>
                        </div>
                        {{ render_navigation(users, 'main.list_users') }}
                    </div>

                </div>
            </div-->
            </div>
        </div><!-- .animated -->
    </div>

    <div class="modal fade" id="fa_modal_window" tabindex="-1" role="dialog" aria-labelledby="fa_modal_label">
        <div class="modal-dialog" role="document">
            <div class="modal-content"></div>
        </div>
    </div>
{% endblock %}